/*
	Script SQL Grupo anterior, proyecto base
*/


START TRANSACTION;
--DROP DATABASE IF EXISTS Gestion_Escuela;
-- CREATE DATABASE IF NOT EXISTS Gestion_Escuela DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci;
-- USE Gestion_Escuela;

CREATE TABLE IF NOT EXISTS Aplicaciones
(
	idAplicacion TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL UNIQUE,
	descripcion VARCHAR(200) NOT NULL,
	url VARCHAR(100) NOT NULL,
	icono VARCHAR(100) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idAplicacion)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Perfiles
(
	idPerfil TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL UNIQUE,
	descripcion VARCHAR(200) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idPerfil)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Aplicaciones_Perfiles
(
	idPerfil TINYINT UNSIGNED,
	idAplicacion TINYINT UNSIGNED,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_Aplicaciones_Perfiles PRIMARY KEY (idPerfil, idAplicacion),
	
	CONSTRAINT FK_Aplicaciones_Perfiles_Perfiles 
		FOREIGN KEY (idPerfil) 
			REFERENCES Perfiles (idPerfil) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Aplicaciones_Perfiles_Aplicaciones 
		FOREIGN KEY (idAplicacion) 
			REFERENCES Aplicaciones (idAplicacion) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Usuarios
(
	idUsuario SMALLINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL,
	correo VARCHAR(60) NOT NULL UNIQUE,
	bajaTemporal BIT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idUsuario)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Perfiles_Usuarios
(
	idPerfil TINYINT UNSIGNED,
	idUsuario SMALLINT UNSIGNED,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_Perfiles_Usuarios PRIMARY KEY (idPerfil, idUsuario),
	
	CONSTRAINT FK_Perfiles_Usuarios_Perfiles 
		FOREIGN KEY (idPerfil) 
			REFERENCES Perfiles (idPerfil) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Perfiles_Usuarios_Usuarios 
		FOREIGN KEY (idUsuario) 
			REFERENCES Usuarios (idUsuario) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Etapas
(
	idEtapa TINYINT UNSIGNED AUTO_INCREMENT,
	codEtapa CHAR(5) NOT NULL UNIQUE,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	idCoordinador SMALLINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idEtapa),
	
	CONSTRAINT FK_Etapas_Usuarios 
		FOREIGN KEY (idCoordinador) 
			REFERENCES Usuarios (idUsuario) 
				ON DELETE SET NULL 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Subetapas
(
	idEtapa TINYINT UNSIGNED,
	idEtapaPadre TINYINT UNSIGNED,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_Subetapas PRIMARY KEY (idEtapa, idEtapaPadre),
	
	CONSTRAINT FK_Subetapas_Etapas
		FOREIGN KEY (idEtapa) 
			REFERENCES Etapas (idEtapa) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Subetapas_EtapasPadre
		FOREIGN KEY (idEtapaPadre) 
			REFERENCES Etapas (idEtapa) 
				ON DELETE CASCADE
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Cursos
(
	idCurso TINYINT UNSIGNED AUTO_INCREMENT,
	codCurso CHAR(5) NOT NULL UNIQUE,
	nombre VARCHAR(40) NULL UNIQUE,
	idEtapa TINYINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idCurso),
	
	CONSTRAINT FK_Cursos_Etapas
		FOREIGN KEY (idEtapa) 
			REFERENCES Etapas (idEtapa) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS FP_Departamentos
(
	idDepartamento TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idDepartamento)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS FP_FamiliasProfesionales
(
	idFamilia TINYINT UNSIGNED AUTO_INCREMENT,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	idDepartamento TINYINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idFamilia),
	
	CONSTRAINT FK_FP_FamiliasProfesionales_FP_Departamentos
		FOREIGN KEY (idDepartamento) 
			REFERENCES FP_Departamentos (idDepartamento) 
				ON DELETE SET NULL
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS FP_Ciclos
(
	idCiclo TINYINT UNSIGNED AUTO_INCREMENT,
	codCiclo CHAR(4) NOT NULL UNIQUE,
	nombre VARCHAR(40) NOT NULL UNIQUE,
	idFamilia TINYINT UNSIGNED NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idCiclo),
	
	CONSTRAINT FK_FP_Ciclos_FP_FamiliasProfesionales
		FOREIGN KEY (idFamilia)
			REFERENCES FP_FamiliasProfesionales (idFamilia) 
				ON DELETE SET NULL 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS FP_Ciclos_Cursos
(
	idCiclo TINYINT UNSIGNED,
	idCurso TINYINT UNSIGNED, 
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_FP_Ciclos_Cursos PRIMARY KEY (idCiclo, idCurso),
	
	CONSTRAINT FK_FP_Ciclos_Cursos_FP_Ciclos
		FOREIGN KEY (idCiclo)
			REFERENCES FP_Ciclos (idCiclo) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_FP_Ciclos_Cursos_Cursos
		FOREIGN KEY (idCurso)
			REFERENCES Cursos (idCurso) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS Secciones
(
	idSeccion SMALLINT UNSIGNED AUTO_INCREMENT,
	codSeccion CHAR(6) NOT NULL UNIQUE,
	nombre VARCHAR(100) NOT NULL UNIQUE,
	idTutor SMALLINT UNSIGNED NULL UNIQUE,
	idCurso TINYINT UNSIGNED NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idSeccion),
	
	CONSTRAINT FK_Secciones_Usuarios
		FOREIGN KEY (idTutor)
			REFERENCES Usuarios (idUsuario) 
				ON DELETE SET NULL 
				ON UPDATE CASCADE,
				
	CONSTRAINT FK_Secciones_Cursos
		FOREIGN KEY (idCurso)
			REFERENCES Cursos (idCurso) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Alumnos
(
	idAlumno INT UNSIGNED AUTO_INCREMENT,
	NIA INT UNSIGNED NOT NULL UNIQUE,
	nombre VARCHAR(60) NOT NULL,
	DNI CHAR(9) NULL,
	idSeccion SMALLINT UNSIGNED NOT NULL,
	correo VARCHAR(60) NULL,
	sexo ENUM('m','f') NOT NULL,
	telefono CHAR(9) NOT NULL,
	telefonoUrgencia CHAR(9) NULL,
	fechaNacimiento DATE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(idAlumno),
	
	CONSTRAINT FK_Alumnos_Secciones
		FOREIGN KEY (idSeccion)
			REFERENCES Secciones (idSeccion) 
				ON DELETE CASCADE 
				ON UPDATE CASCADE
)ENGINE=INNODB;

INSERT INTO
	Perfiles (nombre, descripcion)
VALUES 
	('Administrador', 'Administrador'),
	('Gestor', 'Gestor'),
	('Profesor', 'Profesor'),
	('Tutor', 'Tutor');
COMMIT;

/*------------------------------------------------------------------------------------------------------*/	

CREATE TABLE IF NOT EXISTS ACT_Momentos (
	idMomento TINYINT unsigned NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL UNIQUE,
	ultimoCelebrado CHAR(5),
	fechaInicio_Inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	fechaFin_Inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_momentos_idMomento PRIMARY KEY (`idMomento`)
);

CREATE TABLE IF NOT EXISTS `ACT_Actividades` (
	`idActividad` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`sexo` CHAR(2) NULL default NULL check(sexo = 'M' OR sexo = 'F' OR sexo = 'MX'),
	`nombre` VARCHAR(60) NOT NULL,
	`esIndividual` BIT NOT NULL,
	`idMomento` TINYINT unsigned NOT NULL,
	`numMaxParticipantes` TINYINT unsigned NULL,
	`fechaInicio_Inscripcion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`fechaFin_Inscripcion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`material` VARCHAR(100) NULL,
	`descripcion` VARCHAR(200) NULL,
	`idResponsable` SMALLINT UNSIGNED NOT NULL,
	`tipo_Participacion` CHAR(1) NOT NULL check(tipo_Participacion = 'C' OR tipo_Participacion = 'G'),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_actividades_idActividad PRIMARY KEY (`idActividad`),

	CONSTRAINT fk_ACT_Actividades_idMomento FOREIGN KEY (idMomento) REFERENCES ACT_Momentos(idMomento) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Actividades_idResponsable FOREIGN KEY (idResponsable) REFERENCES Usuarios(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `ACT_Estadisticas_Actividad` (
	`idEstadisticaAlumno` TINYINT unsigned NOT NULL AUTO_INCREMENT,
	`idActividad` TINYINT unsigned NOT NULL,
	`idEtapa` TINYINT unsigned NOT NULL,
	`idMomento` TINYINT unsigned NOT NULL,
	`anioEscolar` CHAR(5) NULL,
	`total_Inscripciones` SMALLINT unsigned NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_estadisticasActividad PRIMARY KEY (`idEstadisticaAlumno`),
	CONSTRAINT fk_ACT_Estadisticas_Actividades_idActividad FOREIGN KEY (idActividad) REFERENCES ACT_Actividades(idActividad) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Estadisticas_Actividades_idEtapa FOREIGN KEY (idEtapa) REFERENCES Etapas(idEtapa) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Estadisticas_Actividades_idMomento FOREIGN KEY (idMomento) REFERENCES ACT_Momentos(idMomento) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS `ACT_Estadisticas_Totales` (
	`idEstadisticaTotal` TINYINT unsigned NOT NULL AUTO_INCREMENT,
	`idEtapa` TINYINT unsigned NOT NULL,
	`idMomento` TINYINT unsigned NOT NULL,
	`anioEscolar` CHAR(5) NULL,
	`total_Alumnos` SMALLINT unsigned NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_ACT_idEstadisticaTotal PRIMARY KEY (`idEstadisticaTotal`),
	CONSTRAINT fk_ACT_Estadisticas_Totales_idMomento FOREIGN KEY (idMomento) REFERENCES ACT_Momentos(idMomento) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Estadisticas_Totales_idEtapa FOREIGN KEY (idEtapa) REFERENCES Etapas(idEtapa) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS `ACT_Actividades_Etapas` (
	`idActividad` TINYINT unsigned NOT NULL,
	`idEtapa` TINYINT unsigned NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_ACT_idActividad_idEtapa PRIMARY KEY (`idActividad`, `idEtapa`),
	CONSTRAINT fk_ACT_Actividades_Etapas_idAlumno FOREIGN KEY ACT_Actividades_Etapas(idActividad) REFERENCES ACT_Actividades(idActividad) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Actividades_Etapas_idActividad FOREIGN KEY ACT_Actividades_Etapas(idEtapa) REFERENCES Etapas(idEtapa) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS `ACT_Inscriben_Secciones` (
	`idActividad` TINYINT unsigned NOT NULL,
	`idSeccion` SMALLINT UNSIGNED NOT NULL,
	`fecha_y_hora_Inscripcion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_ACT_Inscriben_Secciones PRIMARY KEY (`idActividad`, `idSeccion`),
	CONSTRAINT fk_ACT_Inscriben_Secciones_idSeccion FOREIGN KEY (idSeccion) REFERENCES Secciones(idSeccion) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Inscriben_Secciones_idActividad FOREIGN KEY (idActividad) REFERENCES ACT_Actividades(idActividad) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS `ACT_Inscriben_Alumnos` (
	`idAlumno` INT unsigned NOT NULL,
	`idActividad` TINYINT unsigned NOT NULL,
	`fecha_y_hora_Inscripcion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,

	CONSTRAINT PK_ACT_idAlumno PRIMARY KEY (`idAlumno`, `idActividad`),

	CONSTRAINT fk_ACT_Inscriben_Alumnos_idAlumno FOREIGN KEY (idAlumno) REFERENCES Alumnos(idAlumno) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_ACT_Inscriben_Alumnos_idActividad FOREIGN KEY (idActividad) REFERENCES ACT_Actividades(idActividad) ON DELETE CASCADE ON UPDATE CASCADE
);


